import React, { useState } from "react";
import { Link } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { Shield, Zap, Brain, Loader2, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import AuroraBackground from "@/components/AuroraBackground";
import { Client } from "@gradio/client";

export default function PriXplainer() {
  const [policyText, setPolicyText] = useState("");
  const [htmlResult, setHtmlResult] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleScan = async () => {
    if (!policyText.trim()) return;
    
    setIsLoading(true);
    setError(null);
    setHtmlResult(null);

    try {
      const app = await Client.connect("shikhasoneji8/privacywhisper");

      // In your app.py, the final output comes after a .then() chain.
      // We need to call the prediction and ensure we wait for the full output.
      // Try hitting the specific endpoint that generates the HTML (often 1 or 2)
      const result = await app.predict(1, { 
        text_input: policyText, 
        threshold: 0.5 
      });

      // result.data[0] should be the HTML generated by presentation.df_to_html
      if (result.data && result.data[0]) {
        setHtmlResult(result.data[0]);
      } else {
        throw new Error("No analysis data returned. Check the model status.");
      }
      
    } catch (err: any) {
      console.error("API Error:", err);
      setError("The AI server is taking too long to respond. This usually happens if the model is loading on a CPU. Try a shorter snippet.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col min-h-screen">
      <section className="py-16 relative overflow-hidden">
        <AuroraBackground showParticles={true} />
        <div className="section-container relative z-10">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-5xl font-black mb-6 text-gradient">PriXplainer</h1>
            
            <div className="bg-background/40 backdrop-blur-md p-6 rounded-2xl border border-primary/20 shadow-2xl">
              <textarea 
                className="w-full p-4 rounded-xl border border-border bg-background/80 mb-4 h-48 focus:ring-2 focus:ring-primary outline-none text-foreground"
                placeholder="Paste the Privacy Policy text here to begin analysis..."
                value={policyText}
                onChange={(e) => setPolicyText(e.target.value)}
              />
              
              <Button 
                onClick={handleScan} 
                disabled={isLoading || !policyText}
                className="w-full h-14 text-lg font-bold"
                variant="glow"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                    Analyzing with PrivBERT...
                  </>
                ) : (
                  <>Start Privacy Scan <Zap className="ml-2 h-5 w-5" /></>
                )}
              </Button>
            </div>

            <AnimatePresence>
              {error && (
                <motion.div 
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="mt-4 p-4 rounded-xl bg-destructive/10 border border-destructive/30 text-destructive flex items-center gap-3"
                >
                  <AlertCircle className="h-5 w-5" />
                  <p className="text-sm font-medium">{error}</p>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>
      </section>

      {/* Results Section */}
      <section className="py-12 bg-background">
        <div className="section-container">
          {htmlResult ? (
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="prose prose-invert max-w-none"
            >
              <h2 className="text-2xl font-bold mb-6 text-center">Analysis Results</h2>
              {/* This renders the actual HTML cards from app.py */}
              <div dangerouslySetInnerHTML={{ __html: htmlResult }} />
            </motion.div>
          ) : !isLoading && (
            <div className="text-center py-20 border-2 border-dashed border-muted rounded-3xl">
              <Brain className="h-16 w-16 mx-auto text-muted mb-4" />
              <p className="text-muted-foreground font-medium">Results will appear here after analysis.</p>
            </div>
          )}
        </div>
      </section>
    </div>
  );
}